### ISSUE TITLE
Random intercepts model bug

### ISSUE THREAD

**Issue by graemeleehickey** [sambrilleman/rstanjm#70]
The following model

```r
mv1 <- stan_jm(
  formulaLong = list(
    logBili ~ year + (1 | id),
    albumin ~ year + (1 | id)),
  dataLong = pbcLong,
  formulaEvent = Surv(futimeYears, death) ~ 1,
  dataEvent = pbcSurv,
  time_var = "year",
  base_haz = "bs")
```

gives the following error message: `Error in e_mf[, id_var] : subscript out of bounds`

I think it is actually the survival model having `~1` term only.

**Comment by sambrilleman** [comment]
Cheers, should be fixed now! Corrected version saved on github.

**Comment by sambrilleman** [comment]
Woops, I initially only fixed it for Weibull model. Should now also be working for bs and piecewise baseline hazards. Updated on github.
